---
- hosts: all
  become: true
  gather_facts: true
  tasks:
    - name: commentout the existing 127.0.1.1 line in file
      tags: commenthost
      ansible.builtin.lineinfile:
        path: /etc/hosts
        # String to search
        regexp: '(^127.0.1.1 .*)'
        line: '# \1'
        backrefs: true
        state: present
      register: commenthost

    - name: Add IP address and names of all hosts to all hosts
      ansible.builtin.lineinfile:
        dest: /etc/hosts
        regexp: '.*{{ item }}$'
        line: "{{ hostvars[item].ansible_host }} {{item}}"
        state: present
      when: hostvars[item].ansible_host is defined
      with_items: "{{ groups.all }}"