---
- hosts: openstack
  become: true
  gather_facts: true
  tasks:
    - name: install addition packges for openstack
      ansible.builtin.apt:
        name:
          - bridge-utils
          - debootstrap
          - openssh-server
          - tcpdump
          - vlan
          - python3
          - openvswitch-switch
          - vim
        state: present
        update_cache: true

    - name: install the kernel extra package if you have one for your kernel version
      ansible.builtin.shell: sudo apt install linux-modules-extra-$(uname -r)

    - name: Check if reboot required
      ansible.builtin.stat:
        path: /var/run/reboot-required
      register: reboot_required_file

    - name: Reboot if required by overcloud host
      ansible.builtin.reboot:
        msg: "Reboot initiated by Ansible for kernel updates"
        connect_timeout: 5
        reboot_timeout: 300
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: uptime
      when: reboot_required_file.stat.exists == true  