---
- hosts: openstack
  become: true
  gather_facts: true
  tasks:
    - name: Update apt repo and cache on all Debian/Ubuntu boxes
      ansible.builtin.apt: 
        update_cache: true
        force_apt_get: true 
        cache_valid_time: 3600

    - name: Upgrade all packages on servers
      ansible.builtin.apt: 
        upgrade: true 
        force_apt_get: true